# Generated by Django 4.0.4 on 2022-04-13 18:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ability name')),
                ('key', models.CharField(choices=[('passive', 'Passive'), ('q', 'Q'), ('w', 'W'), ('e', 'E'), ('r', 'R')], max_length=7, verbose_name='Select keyboard key of an ability')),
                ('description', models.TextField(verbose_name='Description of an ability')),
            ],
        ),
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Champion name')),
                ('underName', models.CharField(max_length=50, verbose_name='Under name')),
                ('bio', models.TextField(verbose_name='Champion biography')),
                ('quote', models.CharField(max_length=50, verbose_name='Quote')),
                ('releaseDate', models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.', verbose_name='Champion release date')),
                ('priceBe', models.IntegerField(help_text='Enter price of champion in Blue Essence', validators=[django.core.validators.MaxValueValidator(6300), django.core.validators.MinValueValidator(450)])),
                ('role', models.CharField(choices=[('assassin', 'Assassin'), ('fighter', 'Fighter'), ('mage', 'Mage'), ('marksman', 'Marksman'), ('support', 'Support'), ('tank', 'Tank')], help_text='Select role of a champion', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Region name')),
                ('bio', models.TextField(verbose_name='Region biography')),
            ],
        ),
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Skin name')),
                ('releaseDate', models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.', verbose_name='Skin release date')),
                ('priceRp', models.IntegerField(help_text='Enter price of skin in Riot Points', validators=[django.core.validators.MaxValueValidator(3250), django.core.validators.MinValueValidator(390)])),
                ('championName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loldb.champion')),
            ],
        ),
        migrations.AddField(
            model_name='champion',
            name='regionName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loldb.region'),
        ),
    ]
