# Generated by Django 4.0.4 on 2022-04-13 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loldb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='champion',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='champion',
            name='priceBe',
            field=models.IntegerField(help_text='Enter price of champion in Blue Essence', validators=[django.core.validators.MaxValueValidator(6300), django.core.validators.MinValueValidator(450)], verbose_name='Price in Blue Essence'),
        ),
        migrations.AlterField(
            model_name='region',
            name='bio',
            field=models.TextField(null=True, verbose_name='Region biography'),
        ),
    ]
