# Generated by Django 4.0.4 on 2022-04-13 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loldb', '0002_alter_champion_options_alter_champion_pricebe_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='skin',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='champion',
            name='regionName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loldb.region', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='region',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Region biography'),
        ),
    ]
