# Generated by Django 4.0.4 on 2022-04-13 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loldb', '0003_alter_region_options_alter_skin_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Abilities',
            new_name='Abilitie',
        ),
    ]
