# Generated by Django 4.0.4 on 2022-04-13 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loldb', '0004_rename_abilities_abilitie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Abilitie',
            new_name='Ability',
        ),
        migrations.AlterModelOptions(
            name='ability',
            options={'ordering': ['name']},
        ),
    ]
