# Generated by Django 4.0.4 on 2022-04-13 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loldb', '0005_rename_abilitie_ability_alter_ability_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skin',
            name='championName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loldb.champion', verbose_name='Champion name'),
        ),
    ]
