# Generated by Django 4.0.4 on 2022-04-13 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loldb', '0006_alter_skin_championname'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='championName',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loldb.champion', verbose_name='Champion name'),
            preserve_default=False,
        ),
    ]
