# Generated by Django 4.0.4 on 2022-04-24 15:46

from django.db import migrations, models
import loldb.models


class Migration(migrations.Migration):

    dependencies = [
        ('loldb', '0008_remove_champion_undername_champion_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='skin',
            name='skin',
            field=models.ImageField(blank=True, null=True, upload_to=loldb.models.champion_path, verbose_name='Skin'),
        ),
    ]
