# Generated by Django 4.0.4 on 2022-05-12 20:15

from django.db import migrations, models
import loldb.models


class Migration(migrations.Migration):

    dependencies = [
        ('loldb', '0009_skin_skin'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='icon',
            field=models.ImageField(default=1, upload_to=loldb.models.region_icon, verbose_name='Icon'),
            preserve_default=False,
        ),
    ]
