# Generated by Django 4.0.4 on 2022-06-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loldb', '0012_alter_champion_basicskin'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
