# Generated by Django 4.0.4 on 2022-06-04 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loldb', '0013_champion_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champion',
            name='slug',
        ),
    ]
